# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f644b92f21c0c51d8a420b0c300e60f3b8b2700c96a30fd7df4335e31e452dd7b07933da356a9d24a587aaecf23ca19fd62bd214cfc59fa9e9e33a62cfb2639c

test:
  secret_key_base: 1266383948493279a11f6b2e9a9bcfbce8978b09953c18732f49f2592e9a175cc7f2fb57dbb2a84a6db9d42940bf6993c528dde81ccf647124ceadcb2d7d19a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
